Repository MoominBot/MoominBot, pull requests merged in 2021-12, with the labels that each got.

#31 feat: add more fun commands
  src/commands/Fun/FakeMessageCommand.ts
  src/commands/Fun/FeedCommand.ts
  src/interactions/slash/Fun/FakeMessageCommand.ts
  src/interactions/slash/Fun/FeedCommand.ts
Labels: enhancement, priority: medium, semver: minor

#37 feat: add ronb feed subscription support
  package.json
  prisma/migrations/20211201145352_initial/migration.sql
  prisma/schema.prisma
  src/commands/Config/ConfigCommand.ts
  src/commands/Config/subcommands/setRONB.ts
  src/database/prisma.ts
  src/events/DiscordEvents/InteractionEvent.ts
  src/events/DiscordEvents/ReadyEvent.ts
  src/index.ts
  src/interactions/slash/Config/ConfigCommand.ts
  src/jobs/ronb.ts
  src/utils/tokens.ts
  tsconfig.json
Labels: priority: medium, semver: minor, status: pending

#36 feat: add `nick` command
  src/commands/Moderation/ModeratedNickCommand.ts
  src/interactions/slash/Moderation/ModeratedNickCommand.ts
Labels: enhancement, priority: medium, semver: minor

#41 chore: docker setup
  .dockerignore
  .env.example
  Dockerfile
  docker-compose.yml
  entrypoint.sh
  package.json
Labels: devOps

#42 feat(Moderation): add `kick` command
  global.d.ts
  src/commands/Moderation/KickCommand.ts
  src/interactions/slash/Moderation/KickCommand.ts
Labels: enhancement, priority: medium, semver: minor

#44 feat: add neb result command
  src/commands/News/NEBCommand.ts
  src/interactions/slash/News/NEBCommand.ts
  src/tsxLoader.ts
  src/utils/neb.ts
  yarn.lock
Labels: priority: medium, semver: minor

#46 refactor(HelpCommand): add category filter
  src/commands/General/HelpCommand.tsx
  src/commands/General/subcommands/HelpCommand.ts
  src/events/DiscordEvents/InteractionEvent.ts
  src/utils/constants.ts
Labels: priority: low, semver: minor

#47 feat: webhook forwarder and dynamic presence
  .env.example
  src/commands/General/BotinfoCommand.ts
  src/events/DiscordEvents/ErrorEvent.ts
  src/events/DiscordEvents/ReadyEvent.ts
  src/utils/webhookLogger.ts
Labels: priority: low, semver: minor

#48 feat(DevTools): add devtools command
  src/base/BaseCommand.ts
  src/commands/DevTools/DevToolsCommand.ts
  src/commands/General/PingCommand.ts
  src/deployCommands.ts
  src/events/DiscordEvents/ErrorEvent.ts
  src/events/DiscordEvents/ReadyEvent.ts
  src/index.ts
  src/interactions/slash/Config/ConfigCommand.ts
  src/interactions/slash/DevTools/DevCommands.ts
  src/utils/MoominUtils.ts
  src/utils/constants.ts
Labels: priority: medium, semver: minor, status: approved

#60 refactor(BotinfoCommand): add last 3 commits
  src/commands/General/BotinfoCommand.ts
  src/utils/parse_ms.ts
Labels: priority: low, semver: minor
