Repository MoominBot/MoominBot, pull requests merged in 2021-11, with the labels that each got.

#4 chore: add GNU GPL v3.0 License for the repository.
  LICENSE
Labels: priority: high

#2 feat: rashifal command
  .env.example
  package.json
  src/commands/General/RashifalCommand.ts
  src/commands/General/utils/Rashifal.ts
  src/constants.ts
  src/database/redis.ts
  src/index.ts
  src/interactions/slash/General/RashifalCommand.ts
  yarn.lock
Labels: enhancement, priority: medium

#8 chore: Use subpath import
  package.json
  src/commands/General/PingCommand.ts
  src/commands/General/RashifalCommand.ts
  src/commands/General/context/AvatarCommand.ts
  src/commands/General/utils/Rashifal.ts
  src/database/redis.ts
  src/deployCommands.ts
  src/events/DiscordEvents/ErrorEvent.ts
  src/events/DiscordEvents/InteractionEvent.ts
  src/events/DiscordEvents/RatelimitEvent.ts
  src/events/DiscordEvents/ReadyEvent.ts
  src/events/DiscordEvents/WarnEvent.ts
  src/events/ProcessEvents/handlers.ts
  src/index.ts
  src/utils/constants.ts
  src/utils/logger.ts
  tsconfig.json
Labels: enhancement, priority: medium

#12 chore: add license to readme
  LICENSE
  README.md
Labels: documentation, semver: patch

#14 feat: add `userinfo` and `serverinfo` commands
  .eslintrc.json
  .github/dependabot.yml
  .github/workflows/ESLint.yml
  src/commands/General/ServerinfoCommand.ts
  src/commands/General/context/UserinfoCommand.ts
  src/interactions/context/user/UserinfoCommand.ts
  src/interactions/slash/General/ServerinfoCommand.ts
  tsconfig.eslint.json
  tsconfig.json
Labels: enhancement, semver: minor

#13 fix(Rashifal): bind scrape to rashifal
  src/commands/General/utils/Rashifal.ts
Labels: priority: high, semver: patch

#15 feat!: database and cron
  .env.example
  README.md
  package.json
  prisma/migrations/20211126114417_initial/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/commands/General/PingCommand.ts
  src/commands/General/RashifalCommand.ts
  src/commands/General/ServerinfoCommand.ts
  src/commands/General/context/UserinfoCommand.ts
  src/commands/News/RONBCommand.ts
  src/database/redis.ts
  src/events/DiscordEvents/InteractionEvent.ts
  src/index.ts
  src/interactions/slash/News/RONBCommand.ts
  src/jobs/rashifal.ts
  src/jobs/ronb.ts
  src/jobsLoader.ts
  src/utils/Rashifal.ts
  src/utils/constants.ts
  src/utils/safeJSON.ts
  src/utils/tokens.ts
  tsconfig.json
  yarn.lock
Labels: priority: high, semver: major, database

#21 feat: add help command
  global.d.ts
  package.json
  src/base/BaseCommand.ts
  src/commands/General/HelpCommand.tsx
  src/commands/General/PingCommand.ts
  src/commands/General/RashifalCommand.ts
  src/commands/General/ServerinfoCommand.ts
  src/commands/General/context/AvatarCommand.ts
  src/commands/General/context/UserinfoCommand.ts
  src/commands/General/subcommands/HelpCommand.ts
  src/commands/News/RONBCommand.ts
  src/events/DiscordEvents/InteractionEvent.ts
  src/index.ts
  src/interactions/slash/General/HelpCommand.ts
  src/loadTSX.ts
  src/utils/searchEngine.ts
  tsconfig.json
  yarn.lock
Labels: priority: medium, semver: minor

#25 feat: add fun commands
  src/commands/Fun/CuddleCommand.ts
  src/commands/Fun/HugCommand.ts
  src/commands/Fun/KissCommand.ts
  src/commands/Fun/LaughCommand.ts
  src/commands/Fun/SlapCommand.ts
  src/interactions/slash/Fun/CuddleCommand.ts
  src/interactions/slash/Fun/HugCommand.ts
  src/interactions/slash/Fun/KissCommand.ts
  src/interactions/slash/Fun/LaughCommand.ts
  src/interactions/slash/Fun/SlapCommand.ts
Labels: enhancement, priority: medium, in progress
